### ISSUE TITLE
Command line values

### ISSUE THREAD

**Issue by fcohen** [nschaetti/PAN18-Author-Profiling#1]
Thanks for making this code available. I am trying to run it and having problems with the command-line input values. I downloaded the PAN18-Author-Profiling-master.zip from https://pan.webis.de/clef18/pan18-web/author-profiling.html.

I am using the following input values:

python "PAN18-Author-Profiling-master/main.py" --input-dataset "PAN18-Author-Profiling-master/pan18-author-profiling-training-2018-02-27" --output-dir "PAN18-Author-Profiling-master/output" --input-run "PAN18-Author-Profiling-master/models/tweets/en.p" --image-model "PAN18-Author-Profiling-master/models/images/resnet18.p"

I'm seeing this exception.

./run.sh
Traceback (most recent call last):
  File "/Volumes/FrankCohen/Clever Moe dev/PAN18-Author-Profiling-master/main.py", line 56, in <module>
    cuda=args.cuda
  File "/Volumes/FrankCohen/Clever Moe dev/PAN18-Author-Profiling-master/tools/functions.py", line 258, in load_models
    image_model = create_image_model(model_type)
  File "/Volumes/FrankCohen/Clever Moe dev/PAN18-Author-Profiling-master/tools/functions.py", line 238, in create_image_model
    return model
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by benhammoumessaoud** [comment]
what is the password of file : pan18-author-profiling-training-2018-02-27.zip

**Comment by Daanielvb** [comment]
I'm looking for the same thing @benhammoumessaoud , did you manage to find it?

**Comment by fcohen** [comment]
Sorry to say... no. I received no response from this team. :-( -Frank
